# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nitchii-test-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Replace sha
      run: python .github/workflows/replaceCommit.py

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nitchiiapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_55366f1332eb40da9347d30a7c6ec7de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0f4e33e48b14a459190a4eb4fcc62cb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nitchiiapi.azurecr.io/nitchii-api:latest
        file: ./Dockerfile
